/**
 * The C++ standard library surface offered by the editor's completions.
 *
 * This replaces a hand-written list of 38 names. Thirty-eight is enough to
 * look like autocomplete and not enough to be it: typing `std::era` — reaching
 * for `erase` — offered `unordered_map`, `next_permutation` and
 * `prev_permutation`, because `erase` was not in the list and those three were
 * the closest fuzzy matches. A candidate cannot tell "this name does not
 * exist" from "this name is not in our list", so a short list is worse than
 * none: it teaches them to distrust the editor mid-exam.
 *
 * The contest compiles as C++23, so the completions go up to C++23 —
 * `<ranges>`, `<bit>`, `<format>`, `<print>`, `<expected>`, `<flat_map>` and
 * the rest are all things a candidate may legitimately reach for and, until
 * now, would have been silently told did not exist.
 *
 * This is a curated index, not a compiler frontend: it is a flat name list
 * with the owning header, so it cannot know that `.erase` on a `vector` and
 * on a `map` differ, and it will happily offer a name in a scope where it does
 * not apply. That is the accepted trade — a real index means shipping clangd,
 * and the failure mode here is an extra suggestion rather than a missing one.
 *
 * `detail` carries the header, because in a closed exam room "which header do
 * I include" is the question a candidate cannot look up.
 */

import type { Completion } from "@codemirror/autocomplete";

type Group = { header: string; type: Completion["type"]; names: string[] };

const GROUPS: Group[] = [
  {
    header: "<iostream>",
    type: "variable",
    names: ["cin", "cout", "cerr", "clog", "endl", "flush", "ws"],
  },
  {
    header: "<vector>",
    type: "class",
    names: ["vector"],
  },
  {
    header: "container member",
    type: "method",
    names: [
      "push_back",
      "pop_back",
      "push_front",
      "pop_front",
      "emplace",
      "emplace_back",
      "emplace_front",
      "insert",
      "erase",
      "clear",
      "resize",
      "reserve",
      "shrink_to_fit",
      "assign",
      "at",
      "front",
      "back",
      "data",
      "size",
      "empty",
      "capacity",
      "swap",
      "begin",
      "end",
      "rbegin",
      "rend",
      "cbegin",
      "cend",
      "crbegin",
      "crend",
      "find",
      "count",
      "contains",
      "lower_bound",
      "upper_bound",
      "equal_range",
      "extract",
      "merge",
      "try_emplace",
      "insert_or_assign",
      "top",
      "push",
      "pop",
    ],
  },
  {
    header: "<string>",
    type: "method",
    names: [
      "string",
      "wstring",
      "substr",
      "rfind",
      "find_first_of",
      "find_last_of",
      "find_first_not_of",
      "find_last_not_of",
      "replace",
      "append",
      "compare",
      "starts_with",
      "ends_with",
      "c_str",
      "length",
      "npos",
      "to_string",
      "stoi",
      "stol",
      "stoll",
      "stoul",
      "stoull",
      "stof",
      "stod",
      "stold",
      "getline",
      "erase_if",
    ],
  },
  {
    header: "<string_view>",
    type: "class",
    names: ["string_view", "wstring_view"],
  },
  {
    header: "<array>",
    type: "class",
    names: ["array", "to_array"],
  },
  {
    header: "<map>",
    type: "class",
    names: ["map", "multimap"],
  },
  {
    header: "<unordered_map>",
    type: "class",
    names: ["unordered_map", "unordered_multimap"],
  },
  {
    header: "<set>",
    type: "class",
    names: ["set", "multiset"],
  },
  {
    header: "<unordered_set>",
    type: "class",
    names: ["unordered_set", "unordered_multiset"],
  },
  {
    header: "<queue>",
    type: "class",
    names: ["queue", "priority_queue"],
  },
  {
    header: "<deque>",
    type: "class",
    names: ["deque"],
  },
  {
    header: "<stack>",
    type: "class",
    names: ["stack"],
  },
  {
    header: "<list>",
    type: "class",
    names: ["list", "forward_list"],
  },
  {
    header: "<bitset>",
    type: "class",
    names: ["bitset"],
  },
  {
    header: "<utility>",
    type: "function",
    names: [
      "pair",
      "make_pair",
      "move",
      "forward",
      "exchange",
      "swap",
      "declval",
      "cmp_equal",
      "cmp_less",
      "cmp_greater",
      "in_range",
      "to_underlying",
      "unreachable",
    ],
  },
  {
    header: "<tuple>",
    type: "function",
    names: ["tuple", "make_tuple", "tie", "get", "tuple_size", "tuple_cat", "apply", "ignore"],
  },
  {
    header: "<algorithm>",
    type: "function",
    names: [
      "sort",
      "stable_sort",
      "partial_sort",
      "partial_sort_copy",
      "nth_element",
      "is_sorted",
      "is_sorted_until",
      "reverse",
      "reverse_copy",
      "rotate",
      "rotate_copy",
      "shuffle",
      "sample",
      "next_permutation",
      "prev_permutation",
      "is_permutation",
      "lower_bound",
      "upper_bound",
      "equal_range",
      "binary_search",
      "min",
      "max",
      "minmax",
      "min_element",
      "max_element",
      "minmax_element",
      "clamp",
      "count",
      "count_if",
      "find",
      "find_if",
      "find_if_not",
      "find_end",
      "find_first_of",
      "adjacent_find",
      "search",
      "search_n",
      "mismatch",
      "equal",
      "all_of",
      "any_of",
      "none_of",
      "for_each",
      "for_each_n",
      "copy",
      "copy_if",
      "copy_n",
      "copy_backward",
      "move_backward",
      "fill",
      "fill_n",
      "generate",
      "generate_n",
      "transform",
      "remove",
      "remove_if",
      "remove_copy",
      "remove_copy_if",
      "replace",
      "replace_if",
      "unique",
      "unique_copy",
      "partition",
      "stable_partition",
      "partition_point",
      "is_partitioned",
      "merge",
      "inplace_merge",
      "includes",
      "set_union",
      "set_intersection",
      "set_difference",
      "set_symmetric_difference",
      "make_heap",
      "push_heap",
      "pop_heap",
      "sort_heap",
      "is_heap",
      "is_heap_until",
      "lexicographical_compare",
      "lexicographical_compare_three_way",
      "iter_swap",
      "swap_ranges",
      "shift_left",
      "shift_right",
    ],
  },
  {
    header: "<numeric>",
    type: "function",
    names: [
      "accumulate",
      "reduce",
      "transform_reduce",
      "inner_product",
      "partial_sum",
      "exclusive_scan",
      "inclusive_scan",
      "transform_exclusive_scan",
      "transform_inclusive_scan",
      "adjacent_difference",
      "iota",
      "gcd",
      "lcm",
      "midpoint",
    ],
  },
  {
    header: "<ranges> (C++20/23)",
    type: "function",
    names: [
      "ranges",
      "views",
      "filter",
      "take",
      "take_while",
      "drop",
      "drop_while",
      "join",
      "join_with",
      "split",
      "lazy_split",
      "elements",
      "keys",
      "values",
      "zip",
      "zip_transform",
      "adjacent",
      "adjacent_transform",
      "chunk",
      "chunk_by",
      "slide",
      "stride",
      "enumerate",
      "cartesian_product",
      "repeat",
      "as_const",
      "as_rvalue",
      "counted",
      "common",
      "to",
      "subrange",
      "iota_view",
      "single",
    ],
  },
  {
    header: "<bit> (C++20)",
    type: "function",
    names: [
      "popcount",
      "countl_zero",
      "countl_one",
      "countr_zero",
      "countr_one",
      "bit_width",
      "bit_ceil",
      "bit_floor",
      "has_single_bit",
      "rotl",
      "rotr",
      "bit_cast",
      "byteswap",
      "endian",
    ],
  },
  {
    header: "<cmath>",
    type: "function",
    names: [
      "abs",
      "fabs",
      "sqrt",
      "cbrt",
      "pow",
      "exp",
      "exp2",
      "log",
      "log2",
      "log10",
      "sin",
      "cos",
      "tan",
      "asin",
      "acos",
      "atan",
      "atan2",
      "hypot",
      "floor",
      "ceil",
      "round",
      "trunc",
      "fmod",
      "remainder",
      "copysign",
      "isnan",
      "isinf",
      "isfinite",
      "lerp",
    ],
  },
  {
    header: "<optional> (C++17)",
    type: "class",
    names: ["optional", "make_optional", "nullopt", "value_or", "has_value", "and_then", "or_else"],
  },
  {
    header: "<variant> (C++17)",
    type: "class",
    names: ["variant", "get_if", "holds_alternative", "visit", "monostate", "variant_npos"],
  },
  {
    header: "<expected> (C++23)",
    type: "class",
    names: ["expected", "unexpected", "bad_expected_access", "transform_error", "error"],
  },
  {
    header: "<span> (C++20)",
    type: "class",
    names: ["span", "as_bytes", "as_writable_bytes", "subspan", "first", "last"],
  },
  {
    header: "<mdspan> (C++23)",
    type: "class",
    names: ["mdspan", "extents", "dextents", "layout_right", "layout_left"],
  },
  {
    header: "<flat_map> (C++23)",
    type: "class",
    names: ["flat_map", "flat_multimap", "flat_set", "flat_multiset"],
  },
  {
    header: "<generator> (C++23)",
    type: "class",
    names: ["generator"],
  },
  {
    header: "<format> (C++20)",
    type: "function",
    names: ["format", "format_to", "format_to_n", "vformat", "formatted_size", "formatter"],
  },
  {
    header: "<print> (C++23)",
    type: "function",
    names: ["print", "println"],
  },
  {
    header: "<memory>",
    type: "class",
    names: [
      "unique_ptr",
      "shared_ptr",
      "weak_ptr",
      "make_unique",
      "make_shared",
      "allocate_shared",
      "addressof",
      "get",
      "reset",
      "release",
      "make_unique_for_overwrite",
    ],
  },
  {
    header: "<functional>",
    type: "function",
    names: [
      "function",
      "bind",
      "bind_front",
      "bind_back",
      "ref",
      "cref",
      "invoke",
      "invoke_r",
      "hash",
      "less",
      "greater",
      "plus",
      "minus",
      "multiplies",
      "identity",
      "not_fn",
      "move_only_function",
    ],
  },
  {
    header: "<random>",
    type: "class",
    names: [
      "mt19937",
      "mt19937_64",
      "random_device",
      "default_random_engine",
      "uniform_int_distribution",
      "uniform_real_distribution",
      "normal_distribution",
      "bernoulli_distribution",
      "shuffle_order_engine",
    ],
  },
  {
    header: "<chrono>",
    type: "class",
    names: [
      "chrono",
      "steady_clock",
      "system_clock",
      "high_resolution_clock",
      "duration",
      "duration_cast",
      "milliseconds",
      "microseconds",
      "nanoseconds",
      "seconds",
      "minutes",
      "hours",
      "time_point",
      "now",
    ],
  },
  {
    header: "<cstdint>",
    type: "type",
    names: [
      "int8_t",
      "int16_t",
      "int32_t",
      "int64_t",
      "uint8_t",
      "uint16_t",
      "uint32_t",
      "uint64_t",
      "size_t",
      "ptrdiff_t",
      "intmax_t",
      "uintmax_t",
      "__int128",
      "unsigned __int128",
    ],
  },
  {
    header: "<limits>",
    type: "class",
    names: ["numeric_limits", "max", "min", "lowest", "infinity", "epsilon"],
  },
  {
    header: "<concepts> (C++20)",
    type: "interface",
    names: [
      "same_as",
      "derived_from",
      "convertible_to",
      "integral",
      "signed_integral",
      "unsigned_integral",
      "floating_point",
      "totally_ordered",
      "equality_comparable",
      "invocable",
      "predicate",
      "regular",
      "semiregular",
      "movable",
      "copyable",
    ],
  },
  {
    header: "<type_traits>",
    type: "type",
    names: [
      "is_same_v",
      "is_integral_v",
      "is_floating_point_v",
      "is_signed_v",
      "enable_if_t",
      "conditional_t",
      "decay_t",
      "remove_reference_t",
      "remove_cvref_t",
      "common_type_t",
      "underlying_type_t",
      "void_t",
    ],
  },
  {
    header: "<iomanip>",
    type: "function",
    names: [
      "setprecision",
      "fixed",
      "scientific",
      "setw",
      "setfill",
      "hex",
      "oct",
      "dec",
      "boolalpha",
    ],
  },
  {
    header: "<numbers> (C++20)",
    type: "constant",
    names: ["numbers", "pi", "e", "sqrt2", "phi", "ln2", "ln10"],
  },
  {
    header: "<coroutine> (C++20)",
    type: "class",
    names: ["coroutine_handle", "suspend_always", "suspend_never", "noop_coroutine"],
  },
];

/**
 * One entry per name. A name owned by more than one header (`get`, `swap`,
 * `find`, `max`) keeps the first group that claims it, so the list has no
 * duplicates — CodeMirror renders duplicates as separate rows, and two
 * identical labels in a completion popup is worse than one imprecise header.
 */
export const cppStdlibCompletions: Completion[] = (() => {
  const seen = new Set<string>();
  const out: Completion[] = [];
  for (const group of GROUPS) {
    for (const label of group.names) {
      if (seen.has(label)) continue;
      seen.add(label);
      out.push({ label, type: group.type, detail: group.header });
    }
  }
  return out;
})();
