[workspace]
resolver = "2"
members = [
    "apps/desktop/src-tauri",
    "packages/platform-rs",
    "packages/core-rs",
    "packages/network-helper",
]

[workspace.package]
version = "2.0.2"
edition = "2021"
authors = ["Ayush"]
license = "MIT"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.dev]
opt-level = 0
debug = true
