/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: apps/web/src/theme/accessTheme.ts
 * Command: astryx theme build apps/web/src/theme/accessTheme.ts --out apps/web/src/theme/accessTheme.css
 * Generated: 2026-09-30T13:42:12.261Z
 */

/// <reference path="./access.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const accessTheme: DefinedTheme;
