import { defineTheme } from '@astryxdesign/core/theme';
import { neutralTheme } from '@astryxdesign/theme-neutral';

/** Canonical palette. Compile with `pnpm theme:build`; never edit generated files. */
export const accessTheme = defineTheme({
  name: 'access',
  extends: neutralTheme,
  typography: {
    scale: { base: 14, ratio: 1.2 },
    body: { family: 'var(--font-geist-sans)', fallbacks: 'Arial, sans-serif' },
    heading: { family: 'var(--font-geist-sans)', fallbacks: 'Arial, sans-serif', weight: 'semibold' },
    code: { family: 'var(--font-geist-mono)', fallbacks: 'monospace' },
  },
  radius: { base: 3, multiplier: 1 },
  motion: { fast: 120, medium: 200, slow: 320, ratio: 0.75 },
  tokens: {
    '--color-background-body': ['#fafafa', '#0a0a0a'],
    '--color-background-card': ['#ffffff', '#121212'],
    '--color-background-surface': ['#f5f5f5', '#1a1a1a'],
    '--color-background-popover': ['#ffffff', '#1a1a1a'],
    '--color-background-muted': ['#eeeeee', '#202020'],
    '--color-background-inverted': ['#171717', '#f5f5f5'],
    '--color-text-primary': ['#171717', '#f5f5f5'],
    '--color-text-secondary': ['#5b5b5b', '#aaaaaa'],
    '--color-text-disabled': ['#777777', '#777777'],
    '--color-icon-primary': ['#171717', '#f5f5f5'],
    '--color-icon-secondary': ['#5b5b5b', '#aaaaaa'],
    '--color-icon-disabled': ['#777777', '#777777'],
    '--color-border': ['#dedede', '#303030'],
    '--color-border-emphasized': ['#858585', '#767676'],
    '--color-overlay': ['#00000066', '#000000b3'],
    '--color-overlay-hover': ['#0000000a', '#ffffff0a'],
    '--color-overlay-pressed': ['#00000014', '#ffffff14'],
    '--color-neutral': ['#ededed', '#262626'],
    '--color-track': ['#b8b8b8', '#606060'],
    '--color-skeleton': ['#dedede', '#303030'],
    '--color-shadow': ['#00000012', '#00000066'],
    // Purple is reserved for focus, compact active markers, branding and Submit.
    '--color-accent': ['#7c3aed', '#a78bfa'],
    '--color-text-accent': ['#6d28d9', '#c4b5fd'],
    '--color-icon-accent': ['#6d28d9', '#c4b5fd'],
    '--color-on-accent': ['#ffffff', '#171717'],
    '--color-accent-muted': ['#7c3aed14', '#a78bfa14'],
    '--color-background-purple': ['#7c3aed14', '#a78bfa14'],
    '--color-border-purple': ['#7c3aed', '#a78bfa'],
    '--color-text-purple': ['#6d28d9', '#c4b5fd'],
    '--color-icon-purple': ['#6d28d9', '#c4b5fd'],
    '--color-success': ['#15803d', '#4ade80'],
    '--color-text-green': ['#166534', '#86efac'],
    '--color-success-muted': ['#15803d14', '#4ade8014'],
    '--color-border-green': ['#15803d80', '#4ade8080'],
    '--color-warning': ['#a16207', '#fbbf24'],
    '--color-text-yellow': ['#854d0e', '#fcd34d'],
    '--color-warning-muted': ['#a1620714', '#fbbf2414'],
    '--color-border-yellow': ['#a1620780', '#fbbf2480'],
    '--color-error': ['#b91c1c', '#f87171'],
    '--color-text-red': ['#b91c1c', '#fca5a5'],
    '--color-error-muted': ['#b91c1c14', '#f8717114'],
    '--color-border-red': ['#b91c1c80', '#f8717180'],
    '--shadow-low': '0 1px 3px light-dark(#0000000d, #00000040)',
    '--shadow-med': '0 4px 16px light-dark(#00000012, #00000059)',
    '--shadow-high': '0 16px 48px light-dark(#00000024, #00000080)',
    '--shadow-inset-hover': 'inset 0 0 0 2px var(--color-border-emphasized)',
    '--shadow-inset-selected': 'inset 0 0 0 2px var(--color-accent)',
    '--shadow-inset-success': 'inset 0 0 0 2px var(--color-border-green)',
    '--shadow-inset-warning': 'inset 0 0 0 2px var(--color-border-yellow)',
    '--shadow-inset-error': 'inset 0 0 0 2px var(--color-border-red)',
    '--font-size-xs': '0.75rem',
    '--font-size-sm': '0.75rem',
  },
  components: {
    button: {
      'variant:primary': {
        backgroundColor: 'var(--color-background-inverted)',
        color: 'var(--color-background-body)',
        ':hover': { backgroundColor: 'color-mix(in srgb, var(--color-background-inverted), var(--color-background-body) 12%)' },
        ':active': { backgroundColor: 'color-mix(in srgb, var(--color-background-inverted), var(--color-background-body) 20%)' },
      },
      'variant:submit': {
        backgroundColor: 'var(--color-accent)',
        color: 'var(--color-on-accent)',
        ':hover': { backgroundColor: 'color-mix(in srgb, var(--color-accent), var(--color-on-accent) 8%)' },
        ':active': { backgroundColor: 'color-mix(in srgb, var(--color-accent), var(--color-on-accent) 12%)' },
      },
      'variant:destructive': {
        backgroundColor: 'var(--color-error-muted)',
        color: 'var(--color-text-red)',
      },
    },
    badge: {
      'variant:info': { backgroundColor: 'var(--color-background-muted)', color: 'var(--color-text-primary)' },
      'variant:success': { backgroundColor: 'var(--color-success-muted)', color: 'var(--color-text-green)' },
      'variant:warning': { backgroundColor: 'var(--color-warning-muted)', color: 'var(--color-text-yellow)' },
      'variant:error': { backgroundColor: 'var(--color-error-muted)', color: 'var(--color-text-red)' },
    },
    statusdot: {
      'variant:accent': { backgroundColor: 'var(--color-accent)' },
      'variant:success': { backgroundColor: 'var(--color-success)' },
      'variant:warning': { backgroundColor: 'var(--color-warning)' },
      'variant:error': { backgroundColor: 'var(--color-error)' },
    },
    progressbar: {
      // General progress stays neutral; eliminate inherited literal blue override.
      'variant:accent': { '--color-accent': 'var(--color-text-primary)' },
      'variant:success': { '--color-success': 'var(--color-text-green)' },
      'variant:warning': { '--color-warning': 'var(--color-text-yellow)' },
      'variant:error': { '--color-error': 'var(--color-text-red)' },
    },
    banner: {
      'status:info': {
        backgroundColor: 'var(--color-background-muted)',
        '--color-text-primary': 'var(--color-icon-primary)',
        '--color-text-secondary': 'var(--color-icon-secondary)',
        '--color-accent': 'var(--color-icon-primary)',
      },
    },
  },
});
