/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: apps/web/src/theme/accessTheme.ts
 * Command: astryx theme build apps/web/src/theme/accessTheme.ts --out apps/web/src/theme/accessTheme.css
 * Generated: 2026-09-30T13:42:12.260Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Button' {
  interface ButtonVariantMap {
    'submit': true;
  }
}

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
