/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: apps/web/src/theme/accessTheme.ts
 * Command: astryx theme build apps/web/src/theme/accessTheme.ts --out apps/web/src/theme/accessTheme.css
 * Generated: 2026-10-09T14:27:28.472Z
 */

/// <reference path="./access.variants.d.ts" />
import type { DefinedTheme } from "@astryxdesign/core/theme";
export declare const accessTheme: DefinedTheme;
