/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: apps/web/src/theme/accessTheme.ts
 * Command: astryx theme build apps/web/src/theme/accessTheme.ts --out apps/web/src/theme/accessTheme.css
 * Generated: 2026-10-09T14:27:28.472Z
 */

// Generated by astryx theme build
export {};

declare module "@astryxdesign/core/Button" {
  interface ButtonVariantMap {
    submit: true;
  }
}

declare module "@astryxdesign/core/Badge" {
  interface BadgeVariantMap {
    gray: true;
  }
}
