/** Compile Astryx's theme, then derive legacy/WebView adapters from that output. */
import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { tokenDefaults } from '@astryxdesign/core/theme';

const directory = dirname(fileURLToPath(import.meta.url));
const root = resolve(directory, '../../../..');
const result = spawnSync('pnpm', ['exec', 'astryx', 'theme', 'build', 'apps/web/src/theme/accessTheme.ts', '-o', 'apps/web/src/theme/accessTheme.css'], { cwd: root, stdio: 'inherit' });
if (result.status !== 0) process.exit(result.status ?? 1);
const { accessTheme } = await import(pathToFileURL(resolve(directory, 'access.js')).href);
const css = readFileSync(resolve(directory, 'accessTheme.css'), 'utf8');

// Split commas only at the current function level; rgba()/var() commas are nested.
function splitTopLevel(value) {
  const parts = [];
  let depth = 0, start = 0;
  for (let i = 0; i < value.length; i++) {
    if (value[i] === '(' || value[i] === '[') depth++;
    if (value[i] === ')' || value[i] === ']') depth--;
    if (value[i] === ',' && depth === 0) { parts.push(value.slice(start, i).trim()); start = i + 1; }
  }
  parts.push(value.slice(start).trim());
  return parts;
}
function explicitMode(value, mode) {
  while (value.includes('light-dark(')) {
    const start = value.indexOf('light-dark(');
    let end = start + 11, depth = 1;
    for (; end < value.length && depth; end++) {
      if (value[end] === '(') depth++;
      if (value[end] === ')') depth--;
    }
    if (depth) throw new Error(`Unbalanced light-dark expression: ${value}`);
    const pair = splitTopLevel(value.slice(start + 11, end - 1));
    if (pair.length !== 2) throw new Error(`Expected light/dark pair: ${value}`);
    value = value.slice(0, start) + pair[mode === 'light' ? 0 : 1] + value.slice(end);
  }
  return value;
}
const rgb = value => {
  if (!/^#[a-f\d]{6}$/i.test(value)) throw new Error(`Legacy RGB adapter expects a six-digit canonical hex: ${value}`);
  return [1, 3, 5].map(index => parseInt(value.slice(index, index + 2), 16)).join(' ');
};
const accent = mode => `--accent-rgb: ${rgb(explicitMode(accessTheme.tokens['--color-accent'], mode))}; --accent-light-rgb: ${rgb(explicitMode(accessTheme.tokens['--color-text-accent'], mode))};`;
writeFileSync(resolve(directory, 'compatibility.css'), `/* Generated by build-theme.mjs. Canonical source: accessTheme.ts; do not edit. */\n@layer components {\n  :root { ${accent('dark')} }\n  html.light:not(.theme-dark-locked) { ${accent('light')} }\n}\n`);

// Astryx 0.1.8 emits @scope and light-dark(). Keep its output untouched, and
// derive a lower-priority single-root adapter for WebViews without those features.
// Access has one root theme and route dark locks; nested differently named themes
// are intentionally unsupported by this adapter. A future nested theme must extend it.
function blocks(text) {
  const result = [];
  let cursor = 0;
  while (cursor < text.length) {
    const start = text.indexOf('{', cursor);
    if (start === -1) { if (text.slice(cursor).trim()) throw new Error('Unexpected trailing CSS'); break; }
    const selector = text.slice(cursor, start).trim();
    let end = start + 1, depth = 1;
    for (; end < text.length && depth; end++) {
      if (text[end] === '{') depth++;
      if (text[end] === '}') depth--;
    }
    if (depth) throw new Error('Unbalanced generated CSS block');
    result.push({ selector, body: text.slice(start + 1, end - 1) }); cursor = end;
  }
  return result;
}
const rules = [];
function visit(text, layer) {
  for (const block of blocks(text)) {
    if (block.selector.startsWith('@layer ')) visit(block.body, block.selector.slice(7));
    else if (block.selector.startsWith('@scope ')) visit(block.body, layer);
    else {
      if (block.selector.startsWith('@')) throw new Error(`Unsupported generated at-rule: ${block.selector}`);
      // The generated global color-scheme rules are already supplied by globals.css.
      if (block.selector === ':root' || block.selector.startsWith('html[')) continue;
      if (!layer) throw new Error('Generated theme rule has no layer');
      rules.push({ ...block, layer });
    }
  }
}
visit(css.replace(/\/\*[\s\S]*?\*\//g, ''));
const modes = {
  dark: ':where(html:not(.light), html.theme-dark-locked)',
  light: ':where(html.light:not(.theme-dark-locked))',
};
let fallback = '/* Generated by build-theme.mjs from Astryx defaults + accessTheme.css. Do not edit.\n * Single root Access theme adapter: explicit modes, no @scope/light-dark.\n * Imported BEFORE official scoped output; supported browsers use that output. */\n';
for (const [mode, rootSelector] of Object.entries(modes)) {
  const defaults = Object.entries(tokenDefaults).map(([name, value]) => `  ${name}: ${explicitMode(value, mode)};`).join('\n');
  fallback += `@layer astryx-base {\n${rootSelector} {\n${defaults}\n}\n}\n`;
  for (const {selector, body, layer} of rules) {
    const scoped = splitTopLevel(selector).map(part => part === ':scope' ? rootSelector : `${rootSelector} ${part.replace(/:scope/g, '[data-astryx-theme="access"]')}`).join(', ');
    fallback += `@layer ${layer} {\n${scoped} {${explicitMode(body, mode)}}\n}\n`;
  }
}
if (fallback.includes('light-dark(') || /@scope\s*\(/.test(fallback)) throw new Error('Unsupported syntax leaked into adapter');
writeFileSync(resolve(directory, 'fallback.css'), fallback);
console.log('Generated compatibility.css RGB aliases and fallback.css explicit-mode adapter.');
